### ISSUE TITLE
Cannot access website with google login

### ISSUE THREAD

**Issue by cotramarko** [ChristofferGylin/t3-music-app#40]
When trying to log in to the website, the sign-in process with Google fails due to `Access blocked: This app’s request is invalid`, making it impossible to access the site.

<img width="1138" alt="Screenshot 2024-08-29 at 22 34 13" src="https://github.com/user-attachments/assets/8886b526-88d3-4211-a454-6d5006cf77b7">

**Comment by ChristofferGylin** [comment]
That is weird, it works for me on several different computers and accounts, including a freshly created one.

Did you try to log in to the deployed version on https://plinkplonk.io or did you try to run it locally @cotramarko?

**Comment by cotramarko** [comment]
Aha, trying to login via [https://plinkplonk.io/](https://plinkplonk.io/) works! My issue arose when trying to access it via the link in the repo, [https://t3-music-app.vercel.app/](https://t3-music-app.vercel.app/), which causes the login-request to fail.
<img width="467" alt="image" src="https://github.com/user-attachments/assets/6355fb08-54cd-48be-b2ab-40580029661f">

Thanks for the help 👍

**Comment by ChristofferGylin** [comment]
Oh, that shouldn´t be there, thanks for pointing that out @cotramarko, the repo has been updated!
